name: Build Resume PDFs

on:
  push:
    branches: [ main, master ]   # trigger on either default branch
    # Broaden so normal changes trigger a run
    paths:
      - '**.tex'
      - 'src/**'
      - 'Makefile'
      - '.github/workflows/**'
      - 'README.md'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.tex'
      - 'src/**'
      - 'Makefile'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live (minimal but enough for our .tex)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-lmodern \
            latexmk make

      - name: Clean old artifacts
        run: make clean || true

      - name: Build PDFs into pdf/
        run: make

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resumes-pdf
          path: pdf/*.pdf

      - name: Commit updated PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): update generated PDFs in pdf/"
          file_pattern: pdf/*.pdf